require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 128

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'task']
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact